name: 'Remove stale branches'
on:
  pull_request:

jobs:
  stale-branches:
    name: Cleanup stale branches
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./
        with:
          days-before-branch-stale: 15
          dry-run: true
